//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.27 at 09:06:59 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/consulta/retornoProcessamento/v1_1_0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package br.gov.ce.seplag.esocial.mensageiro.schemas;
